### ISSUE TITLE
Add version Tag to release

### ISSUE THREAD

**Issue by smamczak** [dejanskledar/SerializedSwift#1]
Hi, it would be nice to have taged releases of the library instead of downloading master branch

**Comment by smamczak** [comment]
0.2.0 - this format would be good with Xcode because 0.2 doesn't work

**Comment by massimodeluisa** [comment]
@dejanskledar  any news about this?

**Comment by dejanskledar** [comment]
@massimodeluisa  @smamczak Will look into it this evening! Thanks for the response. 😊

**Comment by dejanskledar** [comment]
Should be fixed! Let me know if the issue still persists.

**Comment by smamczak** [comment]
@dejanskledar works great! thanks!
